/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import com.github.cschen1205.ess.engine.RuleInferenceEngine;
import java.awt.event.ItemEvent;
import se.BaseDeConocimiento;
import se.Hechos;

/**
 *
 * @author vicen
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setTitle("Diagnosticar falla");
        //this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_diagnosticar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        so_inicia = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        so_msj_error_gral = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        so_cuelga = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        pantalla_azul = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pitido_largo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        pitido_continuos = new javax.swing.JComboBox<>();
        tres_pitidos_cortos = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        scandisk_activado = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        ruido_metalico = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        pc_enciende = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pantalla_enciende = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        monitor_imagen = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pc_reinicios = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        pc_lenta = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        error_grabar_archivo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultado_diagnostico = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_diagnosticar.setText("Diagnosticar");
        btn_diagnosticar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_diagnosticarActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Sistema Operativo"));
        jPanel2.setToolTipText("");

        jLabel3.setText("S.O. Inicia:");

        so_inicia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Si", "No" }));
        so_inicia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                so_iniciaItemStateChanged(evt);
            }
        });

        jLabel9.setText("S.O. Muestra msjs de Error General:");

        so_msj_error_gral.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Si", "No" }));
        so_msj_error_gral.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                so_msj_error_gralItemStateChanged(evt);
            }
        });

        jLabel10.setText("S.O. se Cuelga:");

        so_cuelga.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Si", "No" }));
        so_cuelga.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                so_cuelgaItemStateChanged(evt);
            }
        });

        jLabel12.setText("Pantalla Azul:");

        pantalla_azul.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Si", "No" }));
        pantalla_azul.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                pantalla_azulItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(so_msj_error_gral, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(144, 144, 144)
                        .addComponent(so_inicia, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(66, 66, 66)
                        .addComponent(so_cuelga, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(70, 70, 70)
                        .addComponent(pantalla_azul, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(68, 68, 68))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(so_cuelga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(so_inicia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(so_msj_error_gral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(pantalla_azul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Inicio de PC"));

        jLabel1.setText("Pitido Largo:");

        pitido_largo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Si", "No" }));
        pitido_largo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                pitido_largoItemStateChanged(evt);
            }
        });

        jLabel7.setText("Pitido Continuos:");

        pitido_continuos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Si", "No" }));
        pitido_continuos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                pitido_continuosItemStateChanged(evt);
            }
        });

        tres_pitidos_cortos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Si", "No" }));
        tres_pitidos_cortos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tres_pitidos_cortosItemStateChanged(evt);
            }
        });

        jLabel8.setText("3 Pitidos Cortos:");

        jLabel15.setText("Scandisk se Activa al Iniciar:");

        scandisk_activado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Si", "No" }));
        scandisk_activado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                scandisk_activadoItemStateChanged(evt);
            }
        });

        jLabel14.setText("Ruido Metalico:");

        ruido_metalico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Si", "No" }));
        ruido_metalico.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ruido_metalicoItemStateChanged(evt);
            }
        });

        jLabel4.setText("PC Enciende:");

        pc_enciende.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Si", "No" }));
        pc_enciende.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                pc_enciendeItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(pitido_largo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(pitido_continuos, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scandisk_activado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tres_pitidos_cortos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ruido_metalico, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(42, 42, 42)
                        .addComponent(pc_enciende, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pitido_largo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(tres_pitidos_cortos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pitido_continuos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel15)
                    .addComponent(scandisk_activado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(ruido_metalico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(pc_enciende, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Monitor"));

        jLabel2.setText("Pantalla Enciende:");

        pantalla_enciende.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Si", "No" }));
        pantalla_enciende.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                pantalla_enciendeItemStateChanged(evt);
            }
        });

        jLabel5.setText("Monitor da Imagen:");

        monitor_imagen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Si", "No" }));
        monitor_imagen.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                monitor_imagenItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pantalla_enciende, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(monitor_imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pantalla_enciende, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(monitor_imagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Rendimiento PC"));

        jLabel6.setText("PC se Reinicia:");

        pc_reinicios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Si", "No" }));
        pc_reinicios.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                pc_reiniciosItemStateChanged(evt);
            }
        });

        jLabel11.setText("PC Lenta:");

        pc_lenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Si", "No" }));
        pc_lenta.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                pc_lentaItemStateChanged(evt);
            }
        });

        jLabel13.setText("Error Grabar Archivo:");

        error_grabar_archivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Si", "No" }));
        error_grabar_archivo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                error_grabar_archivoItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(pc_reinicios, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pc_lenta, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(error_grabar_archivo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(pc_reinicios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(pc_lenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(error_grabar_archivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        resultado_diagnostico.setColumns(20);
        resultado_diagnostico.setRows(5);
        jScrollPane1.setViewportView(resultado_diagnostico);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_diagnosticar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_diagnosticar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pitido_largoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_pitido_largoItemStateChanged
        setFact(Hechos.PITIDO_LARGO, evt);
    }//GEN-LAST:event_pitido_largoItemStateChanged

    private void pantalla_enciendeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_pantalla_enciendeItemStateChanged
        setFact(Hechos.PANTALLA_ENCIENDE, evt);
    }//GEN-LAST:event_pantalla_enciendeItemStateChanged

    private void btn_diagnosticarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_diagnosticarActionPerformed
        _rie.infer();
        
        boolean problema_memoria_ram = false;
        boolean problema_disco_duro = false;
        boolean problema_paca_mother = false;

        if (_rie.getFactsAboutVariable(Hechos.PROBLEMA_MEMORIA_RAM).size() > 0) {
            problema_memoria_ram = true;
        }
        if (_rie.getFactsAboutVariable(Hechos.PROBLEMA_DISCO_DURO).size() > 0) {
            problema_disco_duro = true;
        }
        if (_rie.getFactsAboutVariable(Hechos.PROBLEMA_PLACA_MOTHER).size() > 0) {
            problema_paca_mother = true;
        }
        
        String diagnostico;
        if (problema_memoria_ram || problema_disco_duro || problema_paca_mother) {
            diagnostico = "Posibles problemas: ";
            if (problema_memoria_ram)
                diagnostico += " Memoria Ram";
           
            if (problema_disco_duro)
                diagnostico += ", Disco Duro";
            
            if (problema_paca_mother)
                diagnostico += ", Placa Mother";
        } else {
            diagnostico = "No se pudo determinar el Error.";
        }
        
        resultado_diagnostico.setText(diagnostico);
        
        _rie.clearFacts();
        
        pitido_largo.setSelectedIndex(0);
        pantalla_enciende.setSelectedIndex(0);
        so_inicia.setSelectedIndex(0);
        pc_enciende.setSelectedIndex(0);
        monitor_imagen.setSelectedIndex(0);
        pc_reinicios.setSelectedIndex(0);
        pitido_continuos.setSelectedIndex(0);
        tres_pitidos_cortos.setSelectedIndex(0);
        so_msj_error_gral.setSelectedIndex(0);
        so_cuelga.setSelectedIndex(0);
        pc_lenta.setSelectedIndex(0);
        pantalla_azul.setSelectedIndex(0);
        error_grabar_archivo.setSelectedIndex(0);
        ruido_metalico.setSelectedIndex(0);
        scandisk_activado.setSelectedIndex(0);
    }//GEN-LAST:event_btn_diagnosticarActionPerformed

    private void so_iniciaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_so_iniciaItemStateChanged
        setFact(Hechos.SO_INICIA, evt);
    }//GEN-LAST:event_so_iniciaItemStateChanged

    private void pc_enciendeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_pc_enciendeItemStateChanged
        setFact(Hechos.PC_ENCIENDE, evt);
    }//GEN-LAST:event_pc_enciendeItemStateChanged

    private void monitor_imagenItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_monitor_imagenItemStateChanged
        setFact(Hechos.MONITOR_IMAGEN, evt);
    }//GEN-LAST:event_monitor_imagenItemStateChanged

    private void pc_reiniciosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_pc_reiniciosItemStateChanged
        setFact(Hechos.PC_REINICIOS, evt);
    }//GEN-LAST:event_pc_reiniciosItemStateChanged

    private void pitido_continuosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_pitido_continuosItemStateChanged
        setFact(Hechos.PITIDOS_CONTINUOS, evt);
    }//GEN-LAST:event_pitido_continuosItemStateChanged

    private void tres_pitidos_cortosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tres_pitidos_cortosItemStateChanged
        setFact(Hechos.TRES_PITIDOS_CORTOS, evt);
    }//GEN-LAST:event_tres_pitidos_cortosItemStateChanged

    private void so_msj_error_gralItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_so_msj_error_gralItemStateChanged
        setFact(Hechos.SO_MSJ_FALLA_PROTECCION_GRAL, evt);
    }//GEN-LAST:event_so_msj_error_gralItemStateChanged

    private void so_cuelgaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_so_cuelgaItemStateChanged
        setFact(Hechos.SO_CUELGA, evt);
    }//GEN-LAST:event_so_cuelgaItemStateChanged

    private void pc_lentaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_pc_lentaItemStateChanged
        setFact(Hechos.PC_LENTA, evt);
    }//GEN-LAST:event_pc_lentaItemStateChanged

    private void pantalla_azulItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_pantalla_azulItemStateChanged
        setFact(Hechos.PANTALLA_AZUL, evt);
    }//GEN-LAST:event_pantalla_azulItemStateChanged

    private void error_grabar_archivoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_error_grabar_archivoItemStateChanged
        setFact(Hechos.ERROR_GRABAR_ARCHIVO, evt);
    }//GEN-LAST:event_error_grabar_archivoItemStateChanged

    private void ruido_metalicoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ruido_metalicoItemStateChanged
        setFact(Hechos.RUIDO_METALICO, evt);
    }//GEN-LAST:event_ruido_metalicoItemStateChanged

    private void scandisk_activadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_scandisk_activadoItemStateChanged
        setFact(Hechos.SCANDISK_ACTIVADO, evt);
    }//GEN-LAST:event_scandisk_activadoItemStateChanged

    private void setFact(String hecho, ItemEvent evt) {
        Object item = evt.getItem();

        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (!"none".equals(item.toString().toLowerCase()))
                this._rie.addFact(hecho, item.toString().toLowerCase());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_diagnosticar;
    private javax.swing.JComboBox<String> error_grabar_archivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> monitor_imagen;
    private javax.swing.JComboBox<String> pantalla_azul;
    private javax.swing.JComboBox<String> pantalla_enciende;
    private javax.swing.JComboBox<String> pc_enciende;
    private javax.swing.JComboBox<String> pc_lenta;
    private javax.swing.JComboBox<String> pc_reinicios;
    private javax.swing.JComboBox<String> pitido_continuos;
    private javax.swing.JComboBox<String> pitido_largo;
    private javax.swing.JTextArea resultado_diagnostico;
    private javax.swing.JComboBox<String> ruido_metalico;
    private javax.swing.JComboBox<String> scandisk_activado;
    private javax.swing.JComboBox<String> so_cuelga;
    private javax.swing.JComboBox<String> so_inicia;
    private javax.swing.JComboBox<String> so_msj_error_gral;
    private javax.swing.JComboBox<String> tres_pitidos_cortos;
    // End of variables declaration//GEN-END:variables
    private RuleInferenceEngine _rie = BaseDeConocimiento.getRules(false);
}
